# Copyright 2021 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://pants.readme.io/docs/using-pants-in-ci for tips on how to set up your CI with Pants.

name: Pants
on: [push, pull_request]
concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true
jobs:
  org-check:
    name: Check GitHub Organization
    if: ${{ github.repository_owner == 'pantsbuild' }}
    runs-on: ubuntu-latest
    steps:
      - name: Noop
        run: "true"
  build:
    name: Perform CI Checks
    needs: org-check
    env:
      PANTS_CONFIG_FILES: pants.ci.toml
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Maintain Pants cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache/pants/setup
          ~/.cache/pants/lmdb_store
          ~/.cache/pants/named_caches
        key: ${{ runner.os }}-
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Bootstrap Pants
      run: |
        ./pants --version
    - name: Lint
      run: | 
        ./pants lint ::
    - name: Test
      run: |
        ./pants test ::
    - name: Package
      run: |
        # Smoke test that our `package` implementation runs successfully.
        ./pants package ::
    - name: Upload pants log
      uses: actions/upload-artifact@v2
      with:
        name: pants-log
        path: .pants.d/pants.log
      if: always()  # We want the log even on failures.
